delete from CHARACTER_CLASS;
delete from CHARACTER_RACE;
delete from FACTION;
delete from SKILL;
delete from SKILL_TYPE;
insert into CHARACTER_CLASS(CHARACTER_CLASS_ID, CLASS_NAME, CLASS_DESC) values ('1','Dragon Knight','The powerful Dragon Knight wields the power of fire to dish out serious amounts of damage');
insert into CHARACTER_CLASS(CHARACTER_CLASS_ID, CLASS_NAME, CLASS_DESC) values ('2','Sorcerer','These long range damage dealers have multiple skill trees that allow them to dish out powerful spells.');
insert into CHARACTER_CLASS(CHARACTER_CLASS_ID, CLASS_NAME, CLASS_DESC) values ('3','Templar','The Templar is one of the most diverse classes in the game. Each skill tree allows you to do something different, ranging from tanking to crowd control effects to healing.');
insert into CHARACTER_CLASS(CHARACTER_CLASS_ID, CLASS_NAME, CLASS_DESC) values ('4','Nightblade','The most dedicated DPS class in the game, the Nightblade allows players to deal large amounts of damage, while being heavily focused on stealth.');
insert into CHARACTER_RACE(CHARACTER_RACE_ID, RACE_NAME, RACE_DESC) values ('1','Altmer','Altmer''s are the most magically proficient race in Tamriel.');
insert into CHARACTER_RACE(CHARACTER_RACE_ID, RACE_NAME, RACE_DESC) values ('2','Argonian','Argonian''s are known for high intelligence, breathing under water indefinitely and having natural resistances to disease.');
insert into CHARACTER_RACE(CHARACTER_RACE_ID, RACE_NAME, RACE_DESC) values ('3','Bosmer','Bosmer''s are known for being the best archers on the continent.');
insert into CHARACTER_RACE(CHARACTER_RACE_ID, RACE_NAME, RACE_DESC) values ('4','Breton','Breton''s quick grasp of magic makes them good spellcasters, healers and magic-based characters.');
insert into CHARACTER_RACE(CHARACTER_RACE_ID, RACE_NAME, RACE_DESC) values ('5','Dunmer','Dunmer''s are known to be extremely strong, intelligent, and very quick.');
insert into CHARACTER_RACE(CHARACTER_RACE_ID, RACE_NAME, RACE_DESC) values ('6','Imperial','Imperial''s can be a member of any faction, and their abilities are currently unknown.');
insert into CHARACTER_RACE(CHARACTER_RACE_ID, RACE_NAME, RACE_DESC) values ('7','Khajiit','Khajiit''s make excellent thieves due to their natural stealthiness but are also known to be outstanding warriors.');
insert into CHARACTER_RACE(CHARACTER_RACE_ID, RACE_NAME, RACE_DESC) values ('8','Nord','Nord''s are the physically strongest race, towering above all but the altmer.');
insert into CHARACTER_RACE(CHARACTER_RACE_ID, RACE_NAME, RACE_DESC) values ('9','Orc','Orc''s make perfect tanks. The orcs are tall and powerful. Only nords are larger.');
insert into CHARACTER_RACE(CHARACTER_RACE_ID, RACE_NAME, RACE_DESC) values ('10','Redguard','Redguard''s knowledge of all weapon and armor types, makes many Redguards great warriors or rogue (thief) characters.');
insert into FACTION(FACTION_ID, FACTION_NAME) values ('1','Ebonheart Pact');
insert into FACTION(FACTION_ID, FACTION_NAME) values ('2','Aldmeri Dominion');
insert into FACTION(FACTION_ID, FACTION_NAME) values ('3','Daggerfall Covenant');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('1','Fiery Grip','Pull enemy towards you and deal 11 Fire Damage.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('2','Searing Strike','Deals 11 Flame Damage, and deals 15 Flame Damage over 8.5 seconds. Unlocks at Ardent Flame rank 4.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('3','Fiery Breath','Deals 5 Flame Damage in a cone in front of the player and ignites enemy for 12 Flame Damage over 8 seconds. Unlocks at Ardent Flame rank 20.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('4','Lava Whip','Deals 19 Flame Damage and sets immobile or stunned enemies off balance. Unlocked at Ardent Flame rank 30.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('5','Inferno','Deals 2 Flame Damage to nearby enemies every 1 seconds. Costs 3 Magicka every seconds. Toggle to activate. Unlocks at Ardent Flame rank 42.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('6','Kindling','Increases the damage of burning effects applied by Fire abilities +33%');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('7','Warmth','Causing damage with Ardent Flame abilities snares the targets 15% for 2 seconds.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('8','Searing Heat','Increases duration of Fiery Breath, Searing Strike and Dragonknight Standard abilities by 2 seconds.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('9','World In Flame','Increases damage of fire area of effect abilities by 3%.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('10','Spiked Armor','Increases Armor by 25 for 17 seconds and returns 2 Physical Damage to melee attackers.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('11','Dark Talons','Immobilizes nearby enemies for 3.5 seconds and deals 12 Physical Damage. An ally can activate the Impale Synergy, damaging enemies held within the talons. Unlocks at Draconic Power rank 4.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('12','Dragon Blood','Heals for 27% of missing Health. Increases Health regeneration by 40% for 20 seconds. Unlocks at Dragonic Power rank 20.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('13','Reflective Scale','Reflects all spell projectiles for 4 seconds. Unlocks at Draconic Power rank 30.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('14','Inhale','Absorbs 5 Health from each nearby enemy. After 2.5 seconds, deal 11 Magic Damage to nearby enemies. Unlocks at Draconic Power rank 42.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('15','Iron Skin','Block an additional 5% damage.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('16','Burning Heat','Increases healing received by 6% while a Dragon ability is active.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('17','Elder Dragon','Increases Health regeneration by 2% for each Dragon ability slotted.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('18','Scaled Armor','Increases Spell resistance by 2.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('19','Stonefist','Deals 12 Physical Damage and knocks down enemy for 3 seconds.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('20','Molten Weapons','Increases weapon damage of nearby allies by 1 for 45 seconds. Bonus is increased by 100% on caster. Unlocked at Earthern Heart rank 4.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('21','Obsidian Shield','Creates 17 point damage shield for 20 seconds on all nearby allies. Shield strength is increased 100% on caster. Unlocks at Earthern Heart rank 20.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('22','Petrify','Stuns enemies for 10.5 seconds. Affected targets can take 16 damage before the stun breaks. Unlocks at Earthern Heart rank 30.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('23','Ash Cloud','Snares enemies for 70% and increases their miss chance by 30%. Unlocks at Earthern Heart rank 42.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('24','Eternal Mountain','Increases duration of Earthern Heart abilities by 10%.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('25','Battle Roar','Restores Health, Magicka and Stamina when activating an Ultimate ability. Restore amount increased to 50% of the Ultimate''s cost.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('26','Mountain''s Blessing','Bestows 1 additional Ultimate when activating an Earthern Heart ability.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('27','Helping Hands','Restores 2% Stamina when activating an Earthern Heart ability.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('28','Mage''s Fury','Deals 7 Shock Damage. Explodes for an additional 27 Shock Damage if the target falls below 20% health within 4 seconds. The explosion deals 5 Shock Damage to enemies within a 4m radius of the target.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('29','Lightning Form','Increases Armor and Spell Resistance by 40 for 6 seconds and deals 2 Shock Damage to nearby enemies every 1 second. Unlocked at Storm Calling rank 4.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('30','Lightning Splash','Creates a pool of lightning for 3 seconds that deals 5 Shock Damage every 1 second. A nearby ally may activate Conduit, instantly shocking enemies for 22 Shock Damage. Unlocks at Storm Calling rank 20.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('31','Surge','Increases weapon damage by 3 for 17 seconds. Unlocked at Storm Calling rank 30.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('32','Bolt Escape','Teleports player forward and stuns nearby enemies for 1.5 seconds. Unlocked at Storm Calling rank 42.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('33','Capacitor','Increases Magicka regeneration by 5%.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('34','Energized','Increases damage of Storm Calling abilities by 3%.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('35','Disintegrate','Gives all Lightning spells a 5% chance to instantly disintegrate low Health targets.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('36','Expert Mage','Reduces the cost of Storm Calling spells by 5%.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('37','Unstable Familiar','Summons a familiar to attack enemies. Toggle to activate. Reduces max magicka by 10%.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('38','Daedric Curse','Enemy is cursed for 6 seconds. When effect completes target takes 22 Magic Damage, and nearby enemies take 11 Magic Damage. Only 1 curse may be active at a time.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('39','Summon Winged Twilight','Summons a Winged Twilight to attack nearby enemies. Toggle to activate. Reduces max magicka by 10%.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('40','Bound Armor','Increases armor by 11 when toggled on, but reduces max magicka by 10%.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('41','Conjured Ward','Creates a 23 point damage shield on self and summoned creatures for 20 seconds.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('42','Rebate','Player receives 10% max magicka when one of their summoned creatures is killed.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('43','Power Stone','Reduces the cost of Ultimate abilities by 8%.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('44','Daedric Protection','Increases player''s Health regeneration rate by 10% with any Summoning ability slotted.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('45','Expert Summoner','Provides bonuses for summoned creatures. Winged Twilight has damage increased by 5%, Familiar and Clannfear have movement speed increased by 10% and Atronach has range increased by 15%.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('46','Crystal Shard','Deals 29 Magic Damage to enemy and knocks down for 2 seconds.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('47','Encase','Immobilizes enemies in front of you for 4.5 seconds. Unlocked at Dark Magic rank 4.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('48','Rune Prison','Disorients enemy for 15.1 seconds. Unlocks at Dark Magic rank 20.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('49','Dark Exchange','Restores 12 Health and Magicka while channeling, but drains 23% Stamina per second. Unlocks at Dark Magic rank 30.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('50','Daedric Mines','Summons 3 mines for 30 seconds. Mines take 3 seconds to arm, then deal 13 Magic Damage to a nearby enemy. Enemies damaged by mines are immobilized for 1.5 seconds. Unlocks at Dark Magic rank 42.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('51','Unholy Knowledge','Reduces ability Magicka and Stamina costs by 3%.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('52','Blood Magic','Hitting an enemy with a Dark Magic spell heals player for 3% of their max health.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('53','Persistence','Increases duration of Dark Magic spells by 10%.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('54','Exploitation','Increases Critical Strike chance by 7% when attacking targets affected by Dark Magic.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('55','Assassins''s Blade','Deals 14 Magic Damage. Low health targets take an additional 300% damage.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('56','Teleport Strike','Player moves through the shadows, appearing next to the target. Deals 16 Magic Damage to enemies and stuns monsters for 1.5 seconds. Unlocks at Assassination rank 4.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('57','Blur','Enemies have 15% miss chance when attacking you for 20 seconds. Unlocks at Assassination rank 20.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('58','Mark Target','Marks a target for death. Player''s attacks ignore 75% of target''s Armor and Spell Resistance, and target''s attacks ignore 75% of player''s Armor and Spell resistance. Killing a marked target restores player''s health by 37%. Unlocks at Assassination rank 30.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('59','Haste','For 17 seconds, your attack speed with light and heavy weapons is increased by 30%. Unlocks at Assassination rank 42.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('60','Master Assassin','Increases Weapon Damage while using Invisibility or Stealth by 5%. Successful crouched attacks stun for a longer duration.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('61','Executioner','Killing an enemy with an Assassination ability restores 12 Magicka over 6 seconds.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('62','Pressure Points','Increases Critical Strike rating by 1% for each Assassination ability slotted.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('63','Hemorrhage','Increases bonus Critical Strike damage by 5%.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('64','Shadow Cloak','Gives player invisibility for 2.5 seconds.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('65','Veiled Strike','Deals 22 Magic Damage. If stealthed, attack sets enemy off balance and stuns them for 4 seconds. Unlocks at Shadow rank 4.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('66','Path of Darkness','Enemy targets in front of player take 1 Magic Damage every second for 10 seconds. Paths may only be seen by player and increases movement speed 50% for duration. Unlocks at Shadow rank 20.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('67','Aspect of Terror','Induces fear in 2 nearby enemies for 4 seconds. Unlocks at Shadow rank 30.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('68','Summon Shade','Summons a shade to attack target enemy for 17 seconds. Attacked enemies deal 15% less damage for 4 seconds. Unlocks at Shadow rank 42.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('69','Refreshing Shadows','Increases Stamina regeneration by 15% for 6 seconds when a Shadow ability is activated.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('70','Shadow Barrier','Increases Armor and Spell Resistance by 17 for 4 seconds when coming out of Stealth or Invisibility.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('71','Fortitude','Increases Max Health by 2% for each Shadow ability slotted.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('72','Dark Veil','Increases duration of Shadow abilities by 8%.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('73','Strife','Deals 18 Magic Damage and heals player for 30% of the damage inflicted, every 2 seconds for 10 seconds.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('74','Agony','Stuns enemy for 12 seconds, effect is broken by damage from any source. After effect ends, enemy takes 10 Magic Damage over 5 seconds. Unlocks at Siphoning rank 4.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('75','Cripple','Siphons movement speed from enemy and gives it to player while dealing 25 Magic Damage over 8 seconds. Unlocks at Siphoning rank 20.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('76','Siphoning Strikes','While toggled, basic weapon attacks restore 2% Magicka and Stamina, but deal 23% less damage. 10% chance on basic attack to restore 15% Magicka and Stamina. Unlocks at Siphoning rank 30.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('77','Drain Power','Deals 11 Magic Damage to nearby enemies and increases weapons damage by 6% for each enemy damage, for 17 seconds. Unlocks at Siphoning rank 42.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('78','Catalyst','Increases potion effectiveness by 10%.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('79','Magicka Flood','Increases Max Magicka 4% while a Siphoning ability is slotted.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('80','Soul Siphoner','Increases Healing from Siphoning abilities by 8%.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('81','Transfer','Bestows 1 Ultimate when dealing damage with a Siphoning ability.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('82','Puncturing Strikes','Four consecutive attacks for 2 Magic Damage to enemies in front of you. Closest target takes 100% additional damage and is knocked back on the last hit.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('83','Piercing Javelin','Hurls a spear causing 12 Magic Damage and knocking back target 5 meters. Unlocks at Aedric Spear rank 4.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('84','Focused Charge','Charge to target, interrupting casts and stuns them for 3 seconds. Deals 16 Magic Damage. Unlocks at Aedric Spear rank 20.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('85','Spear Shards','Deals 11 Magic Damage to enemies within target area. Disorients 1 target for 6 seconds. Ally may pick up spear, granting them 25% Stamina and an additional 10 Stamina of 10 seconds. Unlocks at Aedric Spear rank 30.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('86','Sun Shield','Creates damage shield for 27% max Health that lasts 6 seconds. Deals 5 Magic Damage to nearby enemies radius on activation. Each successful hit increases shield strength by 4%. You will not regenerate Magicka while the shield is active. Unlocks at Aedric Spear rank 42.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('87','Piercing Spear','Increases Critical Strike chance by 5%. Increases damage vs. Blocking targets by 5%.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('88','Spear Wall','Increases Block amount vs. melee attacks by +7%.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('89','Burning Light','25% chance on hit to deal 5 Magic Damage.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('90','Balanced Warrior','Increases Weapon Damage by 2% and Spell resistances by 2.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('91','Sun Fire','Deals 12 Flame Damage and an additional 6 Flame Damage over 4.5 seconds. Snares 40% for 4.5 seconds as well.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('92','Solar Flare','Deals 27 Magic Damage to target. Next attack gains 6 Weapon Power and 6 Spell Power against target and nearby enemies. Bonus does not apply to Solar Flare, Dark Flare or Solar Barrage attacks. Unlocks at Dawn''s Wrath rank 4.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('93','Backlash','Target enemy stores up damage taken for 6 seconds. When effect ends they receive an additional 33% of damage inflicted. Unlocks at Dawn''s Wrath rank 20.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('94','Eclipse','Target reflects negative single target Spells back at themselves for 4 seconds. Unlocks at Dawn''s Wrath rank 30.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('95','Blinding Light','Nearby enemies have a 50% chance to miss and be set off balance for 3.5 seconds. Unlocks at Dawn''s Wrath rank 42.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('96','Enduring Ray''s','Increases ability duration by 10%.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('97','Prism','Bestows 1 additional Ultimate upon activating a Sun ability.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('98','Illuminate','Spell resistance is increased by 5 if the attacker is affected by a Dawn''s Wrath ability.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('99','Restoring Spirit','Gain 2% Magicka when activating an ability.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('100','Rushed Ceremony','Heals nearby wounded ally for 33.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('101','Healing Ritual','Heals nearby allies for 22. Heal self for an additional 30%. Unlocks at Restoring Light rank 4.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('102','Restoring Aura','When slotted: Increases stamina and health regeneration by 15. When activated: Increases the health and stamina regeneration of nearby allies by an additional 80% for 6 seconds. Unlocks at Restoring Light rank 20.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('103','Cleansing Ritual','Instantly removes a negative effect from self. Over 12 seconds, heals nearby allies for 2 every 2 seconds. Allies in range may activate Purify, removing all negative effects and healing for 16. Unlocks at Restoring Light rank 30.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('104','Rune Focus','Creates an area of self protection for 12 seconds, increasing Armor and Spell resistance by 25. Unlocks at Restoring Light rank 42.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('105','Mending','Increases Critical Strike chance on allies by up to 15%. Critical Strike chance increases the more Health an ally is missing.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('106','Focused Healing','Increases healing power by 15% to allies standing in an area of protection created by Rite of Passage, Cleansing Ritual or Rune Focus.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('107','Light Weaver','Increases duration of Restoring Aura by 10%. Reduces cost of Healing Ritual by 10%. Gains 13 Armor and Spell resistance while channeling Rite of Passage.');
insert into SKILL(SKILL_ID, SKILL_NAME, SKILL_DESC) values ('108','Master Ritualist','Increases Resurrection speed by 20%. Affected allies resurrect with 50% more Health. 50% chance to gain a soul gem upon successful resurrect.');

